# TODO adapt
version: '3.8'

services:
  web:
    image: nginx:test
    container_name: srcs_nginx
    # build: ./requirements/nginx/
    command: nginx -g "daemon off;"
    # volumes:
    #   - ./services/web/:/usr/src/app/
    ports:
      - 443:443
    env_file:
      - ./.env

