# TODO adapt
version: '3.3'

services:
  mariadb:
    # image: wordpress:test
    build: ./requirements/mariadb/
    volumes: 
      - wordpress_db:/var/lib/mysql:rw
    # Expose: documentation on which port the 
    # application runs inside of docker container
    expose:
      - 3306
    env_file:
      - ./.env
    restart: unless-stopped
    networks:
    - mynetwork

  wordpress:
    #image: wordpress:fpm
    build: ./requirements/wordpress/
    # command: nginx -g "daemon off;"
    # restart: always
    volumes:
      - html:/var/www/html
    expose:
      - 9000
    env_file:
      - ./.env
    restart: unless-stopped
    depends_on:
      - mariadb
    networks:
      - mynetwork
  nginx:
    #image: nginx:latest
    build: ./requirements/nginx/
    #command: nginx -g "daemon off;"
    volumes:
      - html:/var/www/html
    ports:
      - 443:443
    env_file:
      - ./.env
    restart: unless-stopped
    networks:
      - mynetwork
    expose:
      - 443

  redis:
    image: redis:alpine
    depends_on: 
      - wordpress
    ports:
      - 6379:6379
    networks:
      - mynetwork
networks:
  # The default driver depends on how the Docker Engine you’re using is configured, but in most instances it is bridge on a single host and overlay on a Swarm.
  mynetwork:
    driver: bridge

volumes:
  wordpress_db:
     driver_opts:
           type: none
           device: /home/k-stz/data/wordpress #NOTE needs full path (~ doesn't work)
           o: bind
  html:
     driver_opts:
           type: none
           device: /home/k-stz/data/html #NOTE needs full path (~ doesn't work)
           o: bind